
import express , {Request,Response} from "express";
import teacherRoute from './routes/teacherRoute'
import studentRoute from './routes/studentRoute'
import quizRoute from './routes/quizRoute'
import { createConnection  , getRepository} from "typeorm";
import cors from 'cors'
import quizEvaluation from './routes/quizEvaluation'

const app = express();
const port = 4022;
app.use(express.json());
app.use(cors());

createConnection().then(()=>{
    console.log('database connected')
}).catch((error)=>{
    console.log(error)
})
// faqs
const faq = [
    {
      "question": "What is the AI Quiz Generator?",
      "answer": "The AI Quiz Generator is an innovative application that utilizes artificial intelligence to create diverse and dynamic quizzes for students and teachers."
    },
    {
      "question": "How does the AI Quiz Generation work?",
      "answer": "The AI Quiz Generator uses advanced algorithms to analyze question patterns, generate multiple-choice questions, and create unique quizzes based on user preferences."
    },
    {
      "question": "Can I customize the quizzes I create?",
      "answer": "Absolutely! The application allows you to customize quizzes by selecting the topic, number of questions, and type of questions (e.g., Multiple Choice Questions)."
    },
    {
      "question": "Is the AI Quiz Generator suitable for both teachers and students?",
      "answer": "Yes, the AI Quiz Generator caters to both teachers and students. Teachers can create quizzes, and students can participate by joining quizzes generated by their teachers."
    },
    {
      "question": "How do I join a quiz as a student?",
      "answer": "To join a quiz as a student, you need the unique quiz name provided by your teacher. Enter the quiz name, and you'll be ready to start."
    },
    {
      "question": "What types of questions does the AI Quiz Generator support?",
      "answer": "Currently, the AI Quiz Generator supports Multiple Choice Questions (MCQs). However, future updates may include additional question types."
    },
    {
      "question": "Can I review quiz results as a teacher?",
      "answer": "Yes, teachers can review quiz results, including student performance and detailed analytics. The application provides insights into each student's answers."
    },
    {
      "question": "Is my data secure on the AI Quiz Generator?",
      "answer": "We take data security seriously. The application employs encryption protocols, and user data is stored securely. Your privacy is a top priority."
    },
    {
      "question": "How do I reset my password if I forget it?",
      "answer": "If you forget your password, you can use the 'Forgot Password' feature on the login page. Follow the instructions to reset your password securely."
    },
    {
      "question": "Are there any system requirements for using the AI Quiz Generator?",
      "answer": "The AI Quiz Generator is a web-based application, and all you need is a modern web browser with JavaScript enabled. It is compatible with various devices, including desktops, laptops, and tablets."
    }
]



app.use('/auth/teacher' , teacherRoute)
app.use('/auth/student' , studentRoute)
app.use('/quiz' , quizRoute)
app.use('/score' , quizEvaluation)
app.post('/faq' , (req:Request, res:Response)=>{
    res.json(faq)
})

app.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
  });
